### ISSUE TITLE
v13 issue. Payment 

### ISSUE THREAD

**Issue by odoo-mvds** [mollie/mollie-odoo#51]
Hello,

we solved the issue to make the software install on v13 enterprise.
From there on, we were able to configure everything without errors. But the payment gateways are not synched to Odoo. I suppose there is something not working.

Attached screenshot:
![image](https://user-images.githubusercontent.com/59664044/77167998-5cff0e00-6ab7-11ea-86d1-c5118961c9e6.png)

**Comment by ghost** [comment]
Thanks for reporting, we are checking the issue.

**Comment by ghost** [comment]
@odoo-mvds Hello
We have checked for the reported payment gateways issue.
But it is already working properly and always sync the payment gateways to odoo.
![payment_getways_sync](https://user-images.githubusercontent.com/39831642/78018458-89464480-736b-11ea-864b-0c087a8e66ee.png)

It might be the issue is related to an API key or might be the payment gateways are not configured.

**Comment by odoo-mvds** [comment]
Hello,

In v12 it works. But v13 we do not get anything. Even if we put the test
API key. Can you confirm that your test was done in a v13 database?

br,
Met vriendelijke groeten,
<https://www.facebook.com/vdsitsolutions> <http://www.vdsit.be/>
Michael Vandesompel
Zaakvoerder
24/7 SUPPORT:
+32 59 795 111
E‑MAIL SUPPORT:
mv@vdsit.be


Op di 31 mrt. 2020 om 12:53 schreef Odoo Experts B.V. <
notifications@github.com>:

**Comment by ghost** [comment]
@odoo-mvds Hello

This fix will help you more to sync the payment gateways to odoo with the production API key.
https://github.com/mollie/mollie-odoo/pull/56
